const K={role:'s20_role',products:'s20_products',profile:'s20_profile',saved:'s20_saved',tx:'s20_transactions',settings:'s20_settings',store:'s20_store'};
const cats=['Medicine','Food & Restaurant','Grocery & Basic Necessities','Medical / Health Services','Transport','Hotels & Recreation'];
const icons={'Medicine':'💊','Food & Restaurant':'🍽️','Grocery & Basic Necessities':'🛒','Medical / Health Services':'🩺','Transport':'🚌','Hotels & Recreation':'🏨'};
const seed=[
{id:'p1',name:'Generic Medicine',category:'Medicine',description:'Sample medicine listing for the digital booklet.',price:120,eligible:true,active:true,seller:'Participating Pharmacy',branch:'Bacoor'},
{id:'p2',name:'Senior Meal',category:'Food & Restaurant',description:'Sample eligible meal from a participating seller.',price:250,eligible:true,active:true,seller:'Participating Restaurant',branch:'Bacoor'},
{id:'p3',name:'Basic Grocery Pack',category:'Grocery & Basic Necessities',description:'Sample grocery and basic necessities listing.',price:500,eligible:true,active:true,seller:'Participating Grocery',branch:'Bacoor'},
{id:'p4',name:'Basic Consultation',category:'Medical / Health Services',description:'Sample health service listing.',price:600,eligible:true,active:true,seller:'Participating Clinic',branch:'Bacoor'},
{id:'p5',name:'Local Fare',category:'Transport',description:'Sample transport discount listing.',price:80,eligible:true,active:true,seller:'Participating Transport',branch:'Bacoor'},
{id:'p6',name:'Day Recreation Pass',category:'Hotels & Recreation',description:'Sample recreation listing.',price:750,eligible:true,active:true,seller:'Participating Venue',branch:'Bacoor'}
];
let state={view:'home',filter:'All',search:''};
const $=s=>document.querySelector(s); const app=()=>$('#app');
const get=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function init(){if(!localStorage.getItem(K.products))set(K.products,seed);if(!localStorage.getItem(K.profile))set(K.profile,{name:'Senior Citizen',id:'BAC-SC-000001',email:'',phone:''});if(!localStorage.getItem(K.saved))set(K.saved,[]);if(!localStorage.getItem(K.tx))set(K.tx,[]);if(!localStorage.getItem(K.settings))set(K.settings,{font:'normal',contrast:false});if(!localStorage.getItem(K.store))set(K.store,{name:'Participating Seller',branch:'Bacoor',contact:''});render();}
function money(n){return '₱'+Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2400);}
function role(){return localStorage.getItem(K.role)||'';}
function chooseRole(r){localStorage.setItem(K.role,r);state={view:'home',filter:'All',search:''};render();}
function signOut(){state.view='home';render();toast('Role remains locked on this browser.');}
function settings(){return get(K.settings,{font:'normal',contrast:false});}
function setFont(f){const s=settings();s.font=f;set(K.settings,s);render();}
function toggleContrast(){const s=settings();s.contrast=!s.contrast;set(K.settings,s);render();}
function readPage(){if(!('speechSynthesis'in window)){toast('Read aloud is not supported on this browser.');return;}speechSynthesis.cancel();const text=(document.querySelector('main')?.innerText||'').slice(0,5000);speechSynthesis.speak(new SpeechSynthesisUtterance(text));}
function shellClass(){const s=settings();return 'shell '+(s.font==='large'?'large ':s.font==='xlarge'?'xlarge ':'')+(s.contrast?'contrast':'');}
function accessBar(){const s=settings();return `<div class="accessbar"><button class="${s.font==='normal'?'active':''}" onclick="setFont('normal')">A</button><button class="${s.font==='large'?'active':''}" onclick="setFont('large')">A+</button><button class="${s.font==='xlarge'?'active':''}" onclick="setFont('xlarge')">A++</button><button class="${s.contrast?'active':''}" onclick="toggleContrast()">◐ Contrast</button><button onclick="readPage()">🔊 Read</button></div>`;}
function topbar(kind){return `<header class="topbar"><div class="brand"><div class="sealmark">20%</div><div class="brandtext"><strong>${kind==='senior'?'Senior Digital Booklet':'Seller Portal'}</strong><span>Bacoor-inspired blue • gold • ivory</span></div></div><button class="iconbtn" onclick="signOut()" aria-label="Sign out">↪</button></header>`;}
function landing(){app().innerHTML=`<main class="landing"><section class="landinghero"><div class="wrap"><div class="brandbadge"><div class="sealmark">20%</div><span>Senior Digital Booklet</span></div><h1>Your senior discount booklet, made easier to read and use.</h1><p>A mobile-first digital booklet with separate Senior and Seller experiences, large controls, accessibility tools, clear 20% price breakdowns, saved items and transaction records.</p></div></section><section class="rolewrap"><p class="eyebrow">CHOOSE YOUR PORTAL</p><div class="rolegrid"><article class="rolecard"><div class="roleicon">👤</div><h2>Senior Citizen</h2><p>Open your digital ID, find eligible discounts, calculate 20%, review purchases, save items and get help.</p><button class="btn primary" onclick="chooseRole('senior')">Open Senior Portal</button></article><article class="rolecard"><div class="roleicon">🏪</div><h2>Seller</h2><p>Add products and services, manage eligibility, record senior transactions, verify Senior IDs and view reports.</p><button class="btn secondary" onclick="chooseRole('seller')">Open Seller Portal</button></article></div><div class="lockednote"><strong>Portal separation:</strong> after selection, this browser is locked to one role so Seniors do not see Seller controls and Sellers do not see Senior-only screens.</div></section></main>`;}
function render(){if(!role())return landing();role()==='senior'?renderSenior():renderSeller();}
function nav(v){state.view=v;state.search='';if(v!=='catalog'&&v!=='saved')state.filter='All';render();window.scrollTo({top:0,behavior:'smooth'});}
function seniorNav(){return `<nav class="bottomnav"><button class="${state.view==='home'?'active':''}" onclick="nav('home')">🏠<br>Home</button><button class="${state.view==='catalog'?'active':''}" onclick="nav('catalog')">📖<br>Booklet</button><button class="${state.view==='saved'?'active':''}" onclick="nav('saved')">🔖<br>Saved</button><button class="${state.view==='profile'?'active':''}" onclick="nav('profile')">👤<br>My ID</button></nav>`;}
function renderSenior(){app().innerHTML=`<div class="${shellClass()}">${topbar('senior')}${accessBar()}<main class="container">${seniorView()}</main>${seniorNav()}</div>`;}
function seniorView(){switch(state.view){case'catalog':return catalogView(false);case'saved':return catalogView(true);case'calculator':return calculatorView();case'purchases':return purchasesView();case'profile':return profileView();case'help':return helpView();default:return seniorHome();}}
function seniorHome(){const p=get(K.profile,{}),tx=get(K.tx,[]),saved=get(K.saved,[]);const total=tx.reduce((a,t)=>a+Number(t.discount||0),0);return `<section class="hero"><p class="eyebrow">SENIOR CITIZEN PORTAL</p><h1>Hello, ${escapeHtml(p.name||'Senior Citizen')}.</h1><p>Your 20% digital booklet is ready. Use the large buttons below—no complicated menus.</p><div class="idstrip"><div class="roundicon">ID</div><div class="grow"><small>Senior Citizen ID</small><strong>${escapeHtml(p.id||'Not set')}</strong></div><button class="btn outline" onclick="nav('profile')">Show ID</button></div></section><section class="menu"><button class="menucard" onclick="nav('profile')"><span class="mi">🪪</span><span><strong>My Senior ID</strong><small>Show your digital ID</small></span></button><button class="menucard" onclick="nav('catalog')"><span class="mi">🔎</span><span><strong>Find 20% Discounts</strong><small>Browse products and services</small></span></button><button class="menucard" onclick="nav('calculator')"><span class="mi">%</span><span><strong>Discount Calculator</strong><small>See regular, discount and senior price</small></span></button><button class="menucard" onclick="nav('purchases')"><span class="mi">🧾</span><span><strong>My Purchases</strong><small>Review recorded transactions</small></span></button><button class="menucard" onclick="nav('saved')"><span class="mi">🔖</span><span><strong>Saved Items</strong><small>${saved.length} saved item${saved.length===1?'':'s'}</small></span></button><button class="menucard" onclick="nav('help')"><span class="mi">?</span><span><strong>Help</strong><small>Simple step-by-step instructions</small></span></button></section><section class="summary"><div><strong>${money(total)}</strong><span>Recorded savings</span></div><div><strong>${get(K.products,[]).filter(x=>x.active).length}</strong><span>Active listings</span></div></section>`;}
function setFilter(c){state.filter=c;render();}
function setSearch(v){state.search=v;render();setTimeout(()=>{const i=$('#catalogSearch');if(i){i.focus();i.setSelectionRange(v.length,v.length)}},0);}
function openCat(c){state.filter=c;state.view='catalog';render();}
function catalogView(savedOnly){const products=get(K.products,[]).filter(x=>x.active);const saved=get(K.saved,[]);const q=state.search.toLowerCase();const items=products.filter(x=>(state.filter==='All'||x.category===state.filter)&&(!q||`${x.name} ${x.seller} ${x.category} ${x.description}`.toLowerCase().includes(q))&&(!savedOnly||saved.includes(x.id)));return `<section class="page"><p class="eyebrow">${savedOnly?'MY SAVED ITEMS':'20% DIGITAL BOOKLET'}</p><h1>${savedOnly?'Saved Items':'Find Discounts'}</h1><p class="lead">${savedOnly?'Your bookmarked products and services.':'Browse active seller listings and see a clear estimated 20% price breakdown.'}</p><input id="catalogSearch" class="search" placeholder="Search item, service or seller" value="${escapeHtml(state.search)}" oninput="setSearch(this.value)"><div class="chips"><button class="chip ${state.filter==='All'?'active':''}" onclick="setFilter('All')">All</button>${cats.map(c=>`<button class="chip ${state.filter===c?'active':''}" onclick="setFilter('${c.replace(/'/g,"\\'")}')">${icons[c]} ${c}</button>`).join('')}</div>${!savedOnly?`<div class="grid" style="margin:12px 0 16px">${cats.map(c=>`<button class="menucard" onclick="openCat('${c.replace(/'/g,"\\'")}')"><span class="mi">${icons[c]}</span><span><strong>${c}</strong><small>Open category</small></span></button>`).join('')}</div>`:''}<div class="grid">${items.length?items.map(productCard).join(''):`<div class="empty">Nothing here yet. Try another category or search.</div>`}</div></section>`;}
function productCard(x){const d=Number(x.price)*.2,final=Number(x.price)-d,saved=get(K.saved,[]).includes(x.id);return `<article class="card"><span class="tag">${escapeHtml(x.category)}</span><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.description||'Eligible listing from a participating seller.')}</p><div class="sellerline">🏪 <strong>${escapeHtml(x.seller)}</strong>${x.branch?' • '+escapeHtml(x.branch):''}</div><div class="pricebox"><span>Regular price</span><strong>${money(x.price)}</strong><span>You save 20%</span><strong>-${money(d)}</strong><span>Estimated Senior price</span><strong class="final">${money(final)}</strong></div><div class="eligible">✓ ${x.eligible?'Seller marked 20% eligible':'Check eligibility with seller'}</div><div class="actions"><button class="btn outline" onclick="toggleSave('${x.id}')">${saved?'★ Saved':'☆ Save'}</button><button class="btn primary" onclick="speakProduct('${x.id}')">🔊 Read Price</button></div></article>`;}
function toggleSave(id){let s=get(K.saved,[]);s=s.includes(id)?s.filter(x=>x!==id):[...s,id];set(K.saved,s);render();toast(s.includes(id)?'Item saved.':'Removed from saved items.');}
function speakProduct(id){const x=get(K.products,[]).find(p=>p.id===id);if(!x)return;const final=x.price*.8;if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`${x.name}. Regular price ${money(x.price)}. Twenty percent discount ${money(x.price*.2)}. Estimated senior price ${money(final)}.`));}}
function calculatorView(){return `<section class="page"><p class="eyebrow">20% DISCOUNT TOOL</p><h1>Discount Calculator</h1><p class="lead">Enter the regular price. The app will show the 20% discount and estimated Senior price.</p><div class="formcard"><label>Regular price</label><input id="calc" class="field" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0.00" oninput="calcNow()"><div id="calcResult" class="calcresult"><span>20% discount</span><strong>₱0.00</strong><span>Estimated Senior price</span><strong>₱0.00</strong></div><button class="btn primary" style="width:100%;margin-top:12px" onclick="readCalc()">🔊 Read result aloud</button><div class="notice">This is a simple 20% estimate. Final lawful pricing may differ depending on VAT exemption, item eligibility, limits and documentary requirements.</div></div></section>`;}
function calcNow(){const n=Number($('#calc')?.value||0),d=n*.2,f=n-d;$('#calcResult').innerHTML=`<span>20% discount</span><strong>${money(d)}</strong><span>Estimated Senior price</span><strong>${money(f)}</strong>`;}
function readCalc(){const n=Number($('#calc')?.value||0);if('speechSynthesis'in window)speechSynthesis.speak(new SpeechSynthesisUtterance(`Regular price ${money(n)}. Twenty percent discount ${money(n*.2)}. Estimated senior price ${money(n*.8)}.`));}
function purchasesView(){const tx=get(K.tx,[]);return `<section class="page"><p class="eyebrow">PURCHASE HISTORY</p><h1>My Purchases</h1><p class="lead">Transactions recorded by the Seller portal on this browser appear here.</p><div class="history">${tx.length?tx.slice().reverse().map(t=>`<article class="tx"><div class="txhead"><span class="tag">${escapeHtml(t.category)}</span><strong>${money(t.final)}</strong></div><h3>${escapeHtml(t.product)}</h3><p>${escapeHtml(t.seller)} • Receipt ${escapeHtml(t.receipt)}</p><div class="pricebox"><span>Regular total</span><strong>${money(t.original)}</strong><span>Discount saved</span><strong>-${money(t.discount)}</strong></div><button class="btn outline" style="width:100%;margin-top:10px" onclick="findAgain('${t.productId}')">Find item again</button></article>`).join(''):`<div class="empty">No transactions yet.</div>`}</div></section>`;}
function findAgain(id){const x=get(K.products,[]).find(p=>p.id===id);state.view='catalog';state.search=x?.name||'';state.filter='All';render();}
function profileView(){const p=get(K.profile,{});return `<section class="page"><p class="eyebrow">MY SENIOR ID</p><h1>Digital Senior Citizen ID</h1><div class="idcard"><div class="idhead"><div class="sealmark">20%</div><div><small>SENIOR DIGITAL BOOKLET</small><strong>City of Bacoor-inspired branding</strong></div></div><div class="name">${escapeHtml(p.name)}</div><div class="idnumber"><small>Senior Citizen ID</small><strong>${escapeHtml(p.id)}</strong></div><div style="margin-top:16px;color:#ffe6a7;font-weight:800">✓ Senior profile</div></div><button class="btn primary" style="width:100%;margin-top:14px" onclick="readId()">🔊 Read ID aloud</button><div class="formcard"><p class="eyebrow">EDIT MY DETAILS</p><div class="twocol"><div><label>Full name</label><input id="pname" class="field" value="${escapeHtml(p.name)}"></div><div><label>Senior ID number</label><input id="pid" class="field" value="${escapeHtml(p.id)}"></div></div><div class="twocol"><div><label>Email</label><input id="pemail" class="field" value="${escapeHtml(p.email||'')}"></div><div><label>Phone</label><input id="pphone" class="field" value="${escapeHtml(p.phone||'')}"></div></div><button class="btn primary" style="width:100%;margin-top:15px" onclick="saveProfile()">Save My Details</button></div></section>`;}
function saveProfile(){set(K.profile,{name:$('#pname').value.trim()||'Senior Citizen',id:$('#pid').value.trim()||'Not set',email:$('#pemail').value.trim(),phone:$('#pphone').value.trim()});render();toast('Senior profile saved.');}
function readId(){const p=get(K.profile,{});if('speechSynthesis'in window)speechSynthesis.speak(new SpeechSynthesisUtterance(`Senior citizen. ${p.name}. ID number ${p.id}.`));}
function helpView(){return `<section class="page"><p class="eyebrow">HELP</p><h1>How to Use My Booklet</h1><p class="lead">Three simple steps.</p><div class="helpstep"><div class="num">1</div><div><strong>Show your Senior ID</strong><p>Open My Senior ID from the Home screen when a seller needs to verify your ID.</p></div></div><div class="helpstep"><div class="num">2</div><div><strong>Find a discount</strong><p>Tap Find 20% Discounts, choose a category, and check the regular price, discount and estimated Senior price.</p></div></div><div class="helpstep"><div class="num">3</div><div><strong>Review your purchases</strong><p>Seller-recorded transactions appear in My Purchases. Save frequently used items for easier access next time.</p></div></div><div class="notice">Use A, A+, A++ at the top to change text size. Use Contrast for stronger visibility and Read for text-to-speech.</div></section>`;}

function sellerNav(){return `<nav class="bottomnav"><button class="${state.view==='home'?'active':''}" onclick="nav('home')">🏠<br>Home</button><button class="${state.view==='sellerCatalog'?'active':''}" onclick="nav('sellerCatalog')">📦<br>Catalog</button><button class="${state.view==='sale'?'active':''}" onclick="nav('sale')">🧾<br>Sale</button><button class="${state.view==='store'?'active':''}" onclick="nav('store')">🏪<br>Store</button></nav>`;}
function renderSeller(){app().innerHTML=`<div class="${shellClass()}">${topbar('seller')}<main class="container">${sellerView()}</main>${sellerNav()}</div>`;}
function sellerView(){switch(state.view){case'addProduct':return addProductView();case'sellerCatalog':return sellerCatalogView();case'sale':return saleView();case'verify':return verifyView();case'reports':return reportsView();case'store':return storeView();default:return sellerHome();}}
function sellerHome(){const products=get(K.products,[]),tx=get(K.tx,[]),store=get(K.store,{});const sales=tx.reduce((a,t)=>a+Number(t.final||0),0),saved=tx.reduce((a,t)=>a+Number(t.discount||0),0);return `<section class="sellerhero"><p class="eyebrow" style="color:#ffe6a7">SELLER PORTAL</p><h1>${escapeHtml(store.name)}</h1><p>Manage eligible listings and record Senior transactions.</p><div class="sellerstats"><div><strong>${products.length}</strong><span>Listings</span></div><div><strong>${products.filter(x=>x.active).length}</strong><span>Active</span></div><div><strong>${money(sales)}</strong><span>Recorded sales</span></div><div><strong>${money(saved)}</strong><span>Senior savings</span></div></div></section><section class="menu"><button class="menucard" onclick="nav('addProduct')"><span class="mi">＋</span><span><strong>Add Product / Service</strong><small>Publish a new listing</small></span></button><button class="menucard" onclick="nav('sellerCatalog')"><span class="mi">📦</span><span><strong>Manage Catalog</strong><small>Edit status and eligibility</small></span></button><button class="menucard" onclick="nav('sale')"><span class="mi">🧾</span><span><strong>Record Senior Sale</strong><small>Create a transaction</small></span></button><button class="menucard" onclick="nav('verify')"><span class="mi">✓</span><span><strong>Verify Senior ID</strong><small>Check saved Senior profile</small></span></button><button class="menucard" onclick="nav('reports')"><span class="mi">📊</span><span><strong>Reports</strong><small>Sales and savings summary</small></span></button><button class="menucard" onclick="nav('store')"><span class="mi">🏪</span><span><strong>Store Profile</strong><small>Business name and branch</small></span></button></section>`;}
function addProductView(){const store=get(K.store,{});return `<section class="page"><p class="eyebrow">SELLER CATALOG</p><h1>Add Product or Service</h1><div class="formcard"><label>Product / service name</label><input id="aname" class="field" placeholder="Example: Generic Medicine"><label>Category</label><select id="acat" class="field">${cats.map(c=>`<option>${c}</option>`).join('')}</select><label>Description</label><textarea id="adesc" class="field" placeholder="Short description"></textarea><div class="twocol"><div><label>Regular price</label><input id="aprice" class="field" type="number" min="0" step="0.01"></div><div><label>Branch</label><input id="abranch" class="field" value="${escapeHtml(store.branch||'Bacoor')}"></div></div><label><input id="aeligible" type="checkbox" checked> Mark as 20% discount eligible</label><label><input id="aactive" type="checkbox" checked> Active / visible to Senior portal</label><button class="btn primary" style="width:100%;margin-top:16px" onclick="addProduct()">Publish Listing</button></div></section>`;}
function addProduct(){const name=$('#aname').value.trim(),price=Number($('#aprice').value);if(!name||!price){toast('Enter a name and price.');return;}const store=get(K.store,{}),arr=get(K.products,[]);arr.push({id:'p'+Date.now(),name,category:$('#acat').value,description:$('#adesc').value.trim(),price,eligible:$('#aeligible').checked,active:$('#aactive').checked,seller:store.name,branch:$('#abranch').value.trim()});set(K.products,arr);state.view='sellerCatalog';render();toast('Listing published and synced on this browser.');}
function sellerCatalogView(){const arr=get(K.products,[]);return `<section class="page"><p class="eyebrow">SELLER CATALOG</p><h1>Manage Listings</h1><p class="lead">Active listings appear in the Senior booklet on this browser.</p>${arr.length?arr.map(x=>`<article class="productrow"><div><span class="tag">${escapeHtml(x.category)}</span><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.seller)}${x.branch?' • '+escapeHtml(x.branch):''}</p><button class="btn ghost" onclick="toggleProduct('${x.id}')">${x.active?'Set Inactive':'Set Active'}</button><button class="btn ghost" onclick="toggleEligible('${x.id}')">${x.eligible?'Remove 20% Mark':'Mark 20% Eligible'}</button></div><div class="right"><strong>${money(x.price)}</strong><br><span class="status ${x.active?'live':'off'}">${x.active?'ACTIVE':'INACTIVE'}</span><br><button class="btn ghost" onclick="deleteProduct('${x.id}')">Delete</button></div></article>`).join(''):`<div class="empty">No listings yet.</div>`}</section>`;}
function mutateProduct(id,fn){const arr=get(K.products,[]).map(x=>x.id===id?fn({...x}):x);set(K.products,arr);render();}
function toggleProduct(id){mutateProduct(id,x=>({...x,active:!x.active}));}
function toggleEligible(id){mutateProduct(id,x=>({...x,eligible:!x.eligible}));}
function deleteProduct(id){if(!confirm('Delete this listing?'))return;set(K.products,get(K.products,[]).filter(x=>x.id!==id));render();}
function saleView(){const arr=get(K.products,[]).filter(x=>x.active),p=get(K.profile,{});return `<section class="page"><p class="eyebrow">TRANSACTION</p><h1>Record Senior Sale</h1><div class="formcard"><label>Senior ID number</label><input id="sid" class="field" value="${escapeHtml(p.id||'')}"><label>Product / service</label><select id="sproduct" class="field" onchange="salePreview()">${arr.map(x=>`<option value="${x.id}">${escapeHtml(x.name)} — ${money(x.price)}</option>`).join('')}</select><div class="twocol"><div><label>Quantity</label><input id="sqty" class="field" type="number" min="1" value="1" oninput="salePreview()"></div><div><label>Receipt number</label><input id="sreceipt" class="field" value="R-${Date.now().toString().slice(-6)}"></div></div><div id="salePreview" class="calcresult"></div><button class="btn primary" style="width:100%;margin-top:15px" onclick="recordSale()">Record Transaction</button></div></section>`;}
function salePreview(){const x=get(K.products,[]).find(p=>p.id===$('#sproduct')?.value),q=Math.max(1,Number($('#sqty')?.value||1));if(!x)return;const original=x.price*q,d=x.eligible?original*.2:0;const el=$('#salePreview');if(el)el.innerHTML=`<span>Regular total</span><strong>${money(original)}</strong><span>20% discount</span><strong>-${money(d)}</strong><span>Senior price</span><strong>${money(original-d)}</strong>`;}
function recordSale(){const x=get(K.products,[]).find(p=>p.id===$('#sproduct').value),q=Math.max(1,Number($('#sqty').value||1)),sid=$('#sid').value.trim();if(!x||!sid){toast('Choose a product and enter Senior ID.');return;}const original=x.price*q,discount=x.eligible?original*.2:0,tx=get(K.tx,[]);tx.push({id:'t'+Date.now(),productId:x.id,product:x.name,category:x.category,seller:x.seller,seniorId:sid,qty:q,receipt:$('#sreceipt').value.trim()||'N/A',original,discount,final:original-discount,date:new Date().toISOString()});set(K.tx,tx);state.view='home';render();toast('Discount Recorded Successfully ✓');}
function verifyView(){return `<section class="page"><p class="eyebrow">VERIFICATION</p><h1>Verify Senior ID</h1><div class="formcard"><label>Senior Citizen ID number</label><input id="vid" class="field" placeholder="Enter ID"><button class="btn primary" style="width:100%;margin-top:14px" onclick="verifyId()">Verify</button><div id="verifyResult"></div></div></section>`;}
function verifyId(){const p=get(K.profile,{}),v=$('#vid').value.trim();const ok=v&&v.toLowerCase()===String(p.id||'').toLowerCase();$('#verifyResult').innerHTML=ok?`<div class="notice" style="border-color:#9dbba8;background:#edf5ef;color:#3d674d"><strong>✓ Senior profile found</strong><br>${escapeHtml(p.name)} • ${escapeHtml(p.id)}</div>`:`<div class="notice" style="border-color:#d8aaa6;background:#fff0ee;color:#8b3935"><strong>No matching Senior profile on this browser.</strong></div>`;}
function reportsView(){const tx=get(K.tx,[]),sales=tx.reduce((a,t)=>a+Number(t.final||0),0),disc=tx.reduce((a,t)=>a+Number(t.discount||0),0),orig=tx.reduce((a,t)=>a+Number(t.original||0),0);return `<section class="page"><p class="eyebrow">REPORTS</p><h1>Sales & Senior Savings</h1><div class="summary"><div><strong>${tx.length}</strong><span>Transactions</span></div><div><strong>${money(sales)}</strong><span>Senior-price sales</span></div><div><strong>${money(orig)}</strong><span>Regular value</span></div><div><strong>${money(disc)}</strong><span>Total discounts</span></div></div><div class="history" style="margin-top:16px">${tx.slice().reverse().map(t=>`<article class="tx"><div class="txhead"><strong>${escapeHtml(t.product)}</strong><strong>${money(t.final)}</strong></div><p>Senior ID ${escapeHtml(t.seniorId)} • ${escapeHtml(t.receipt)}</p></article>`).join('')||'<div class="empty">No transactions yet.</div>'}</div></section>`;}
function storeView(){const s=get(K.store,{});return `<section class="page"><p class="eyebrow">STORE PROFILE</p><h1>Seller Details</h1><div class="formcard"><label>Business name</label><input id="stname" class="field" value="${escapeHtml(s.name||'')}"><label>Branch</label><input id="stbranch" class="field" value="${escapeHtml(s.branch||'')}"><label>Contact</label><input id="stcontact" class="field" value="${escapeHtml(s.contact||'')}"><button class="btn primary" style="width:100%;margin-top:15px" onclick="saveStore()">Save Store Profile</button><div class="notice">This GitHub Pages version stores data in this browser. A connected cloud database is required for real cross-device Seller-to-Senior syncing.</div></div></section>`;}
function saveStore(){const s={name:$('#stname').value.trim()||'Participating Seller',branch:$('#stbranch').value.trim(),contact:$('#stcontact').value.trim()};set(K.store,s);const arr=get(K.products,[]).map(x=>({...x,seller:x.seller==='Participating Seller'?s.name:x.seller}));set(K.products,arr);render();toast('Store profile saved.');}

window.addEventListener('storage',e=>{if(Object.values(K).includes(e.key))render();});
window.addEventListener('DOMContentLoaded',()=>{init();setTimeout(()=>{if(state.view==='sale')salePreview()},0)});
window.chooseRole=chooseRole;window.signOut=signOut;window.setFont=setFont;window.toggleContrast=toggleContrast;window.readPage=readPage;window.nav=nav;window.setFilter=setFilter;window.setSearch=setSearch;window.openCat=openCat;window.toggleSave=toggleSave;window.speakProduct=speakProduct;window.calcNow=calcNow;window.readCalc=readCalc;window.findAgain=findAgain;window.saveProfile=saveProfile;window.readId=readId;window.addProduct=addProduct;window.toggleProduct=toggleProduct;window.toggleEligible=toggleEligible;window.deleteProduct=deleteProduct;window.salePreview=salePreview;window.recordSale=recordSale;window.verifyId=verifyId;window.saveStore=saveStore;
